### PR TITLE
Patching hiveConf for https://issues.apache.org/jira/browse/HIVE-23700

### PR DESCRIPTION
**Pull request by uptycs-anudeep**

### CODE REVIEW

**Comment by spasam** [comment]
Are these branches based off of https://github.com/Uptycs/uptycs-hive/releases/tag/rel%2Frelease-2.3.7 tag?
Also pom.xml need to be updated so that it builds the custom version jar that won't conflict

**Review by spasam — APPROVED** [review]

**Comment by uptycs-anudeep** [comment]
> Are these branches based off of https://github.com/Uptycs/uptycs-hive/releases/tag/rel%2Frelease-2.3.7 tag?
> Also pom.xml need to be updated so that it builds the custom version jar that won't conflict

yes rel/release-2.3.7
Updated version

**Comment by spasam** [comment]
druid-handler/README.md accidentally updated?

**Review by spasam — APPROVED** [review]

**Comment by uptycs-anudeep** [comment]
> druid-handler/README.md accidentally updated?
Not sure why is it showing up as deleted in diff.

**Pull request merged**
